version: 0.0
os: linux
files:
  - source: .output/
    destination: /usr/share/nginx/jamfluencer-web
permissions:
  - object: /usr/share/nginx
    owner: nginx
    group: nginx
    mode: 775
hooks:
  AfterInstall:
    - location: .aws/startup.sh