version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npx nuxi generate
artifacts:
  files:
    - '.output/public/**/*'
    - 'appspec.yml'
  name: jam-web-$(date +%Y-%m-%d)